export const NEXT_PUBLIC_BACKEND_URL = process.env.NEXT_PUBLIC_BACKEND_URL;
export const NEXT_PUBLIC_API_VERSION = process.env.NEXT_PUBLIC_API_VERSION;
export const NEXT_PUBLIC_API_URL = process.env.NEXT_PUBLIC_API_URL;
export const NEXTAUTH_URL = process.env.NEXTAUTH_URL;
export const NEXT_PUBLIC_SITE_URL = process.env.NEXT_PUBLIC_SITE_URL;
export const NEXTAUTH_SECRET = process.env.NEXTAUTH_SECRET;
export const NEXTAUTH_JWT_SECRET = process.env.NEXTAUTH_JWT_SECRET;
export const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID;
export const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET;
export const ENV = process.env.ENV;
export const NEXT_PUBLIC_CLOUDINARY_PRESET =
  process.env.NEXT_PUBLIC_CLOUDINARY_PRESET;
export const NEXT_PUBLIC_CLOUDINARY_NAME =
  process.env.NEXT_PUBLIC_CLOUDINARY_NAME;
export const NEXT_PUBLIC_API_THEMOVIEDB_KEY =
  process.env.NEXT_PUBLIC_API_THEMOVIEDB_KEY;
export const NEXT_PUBLIC_API_THEMOVIEDB_URL =
  process.env.NEXT_PUBLIC_API_THEMOVIEDB_URL;
export const THEMOVIEDB_IMAGE_URL =
  process.env.NEXT_PUBLIC_API_THEMOVIEDB_IMAGE_URL;
export const NEXT_PUBLIC_API_KKPHIM_IMAGE_URL =
  process.env.NEXT_PUBLIC_API_KKPHIM_IMAGE_URL;
export const NEXT_PUBLIC_GROUP_CHAT_ID = process.env.NEXT_PUBLIC_GROUP_CHAT_ID;
export const NEXT_PUBLIC_CRAWL_MOVIES_URL =
  process.env.NEXT_PUBLIC_CRAWL_MOVIES_URL;
export const NEXT_PUBLIC_API_THEMOVIEDB_IMAGE_URL =
  process.env.NEXT_PUBLIC_API_THEMOVIEDB_IMAGE_URL;
